sudo: required
dist: trusty
language: node_js
node_js:
- 6
before_install:
- openssl aes-256-cbc -K $encrypted_ecc987ece1d6_key -iv $encrypted_ecc987ece1d6_iv
  -in deploy_key.enc -out deploy_key -d
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- ng build --prod
script:
- ng test --single-run --code-coverage --reporters=coverage-istanbul
- ng lint --format=stylish
after_success:
- bash <(curl -s https://codecov.io/bash)
- bash ./deploy.sh
cache:
  directories: node_modules
branches:
  only:
  - master
